version: '2.1'
services:
  redis:
    image: redis

  cache-webserver:
    image: cache-webserver
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      - CACHE_REDIS_SERVER=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_EXPIRY=180
      - CACHE_CAPACITY=10
