version: '2.1'
services:
  redis:
    image: redis

  segment-webserver:
    image: segment-webserver
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      - SEGMENT_REDIS_SERVER=redis
      - SEGMENT_REDIS_PORT=6379
      - SEGMENT_CACHE_EXPIRY=180
      - SEGMENT_CACHE_CAPACITY=10
